name: Validate Configuration

on:
  workflow_dispatch:
    inputs:
      master_list_method:
        description: 'Master list method (youtube_api or ytdlp)'
        required: true
        default: 'youtube_api'
        type: choice
        options:
          - youtube_api
          - ytdlp
      transcript_method:
        description: 'Transcript method (ytdlp or youtube_transcript_api)'
        required: true
        default: 'youtube_transcript_api'
        type: choice
        options:
          - ytdlp
          - youtube_transcript_api
      use_proxy:
        description: 'Enable Webshare proxy'
        required: false
        default: false
        type: boolean
      use_cookies:
        description: 'Enable cookies for yt-dlp'
        required: false
        default: false
        type: boolean

jobs:
  validate-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create configuration file
      run: |
        cat > config.env << EOF
        # Video List Automation Configuration
        
        # Master List Method (youtube_api or ytdlp)
        MASTER_LIST_METHOD=${{ inputs.master_list_method }}
        
        # Transcript Method (ytdlp or youtube_transcript_api)
        TRANSCRIPT_METHOD=${{ inputs.transcript_method }}
        
        # YouTube API Configuration
        YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}
        
        # File Paths
        MASTER_FILE=data/videos_master.json
        CHANNEL_URL=https://www.youtube.com/@AdamSeekerOfficial
        
        # Update Settings
        MAX_VIDEOS_PER_UPDATE=50
        UPDATE_FREQUENCY=manual
        
        # yt-dlp Configuration (optional)
        YTDLP_COOKIES_FILE=${{ inputs.use_cookies == 'true' && './cookies.txt' || '' }}
        YTDLP_USE_PROXY=${{ inputs.use_proxy == 'true' && 'true' || 'false' }}
        
        # Proxy Configuration (optional)
        WEBSHARE_PROXY_USERNAME=${{ secrets.WEBSHARE_PROXY_USERNAME }}
        WEBSHARE_PROXY_PASSWORD=${{ secrets.WEBSHARE_PROXY_PASSWORD }}
        WEBSHARE_PROXY=${{ inputs.use_proxy == 'true' && format('http://{0}:{1}@proxy.webshare.io:80', secrets.WEBSHARE_PROXY_USERNAME, secrets.WEBSHARE_PROXY_PASSWORD) || '' }}
        
        # Notification Settings
        DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}
        EMAIL_NOTIFICATIONS=false
        
        # Categories (comma-separated)
        DEFAULT_CATEGORIES=critique-of-islam,theology,apologetics,debate
        EOF
        
    - name: Create necessary directories
      run: |
        mkdir -p data/transcripts
        mkdir -p logs
        
    - name: Create cookies file if needed
      if: inputs.use_cookies == 'true'
      run: |
        echo "# Netscape HTTP Cookie File" > cookies.txt
        echo "# This is a generated file! Do not edit." >> cookies.txt
        echo "# Add your cookies here if needed" >> cookies.txt
        
    - name: Validate configuration
      run: |
        python scripts/validate_config.py
        
    - name: Run demo
      run: |
        python scripts/demo_configurable_system.py
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: validation-logs-${{ github.run_number }}
        path: logs/